name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Docker image
    run: |
      docker login -u ${{ secrets.DOCKER_USERNAME  }} -p ${{ secrets.DOCKER_PASSWORD  }}
      docker build -t haruiz/falconcv -f docker/Dockerfile .
      docker push haruiz/falconcv:latest
